version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/
hooks:
  # BeforeInstall:
  #   - location: scripts/install_dependencies.sh
  #     timeout: 300
  #     runas: root
  AfterInstall:
    - location: /tmp/scripts/create_vhost.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /tmp/scripts/active_vhost.sh
    # - location: scripts/create_test_db.sh
      timeout: 300
      runas: root
  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 300
  #     runas: root
